Parameters:
  Region: "cn-hangzhou"
  Name: "start-mcp"
SceneMetadata:
  Name:
    zh-cn: "MCP Server"
  Description:
    zh-cn: "MCP Server 官方示例，基于 SSE 协议"
  Logo: "gray/resources/icons/scence_logo.png"
  Visible: true
SceneProfiles:
  - DisplayName:
      zh-cn: MCP Server
    DeployType: SaeFlow
    Documentation:
      zh-cn: "gray/docs/zh-cn/index.md"
    Spec: "gray/templates/cicd.spec.yml"
    Template: "gray/templates/cicd.yml"
    FormTemplate: "gray/templates/form.yml"

