apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sae.aliyun.com/micro-registration: "0"
    sae.aliyun.com/pvtz-discovery-svc: '{"enable":"true","namespaceId":"${REGION_ID}:${NAMESPACE}","portAndProtocol":{"3000:TCP":"3000"},"portProtocols":[],"pvtzDiscoveryName":"${REGION_ID}-${ACCOUNT_ID}","serviceName":"dify-web.${NAMESPACE}"}'
    sae.aliyun.com/security-group-id: ${SECURITY_GROUP_ID}
    sae.aliyun.com/timezone: Asia/Shanghai
    sae.aliyun.com/type: Image
    sae.aliyun.com/vpc-id: ${VPC_ID}
    sae.aliyun.com/vswitch-list: ${VSWITCH_LIST}
  name: dify-web
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      sae.aliyun.com/app-name: dify-web
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        sae.aliyun.com/app-name: dify-web
    spec:
      containers:
      - env:
        - name: APP_API_URL
        - name: CONSOLE_API_URL
        - name: EDITION
          value: SELF_HOSTED
        image: registry.cn-shenzhen.aliyuncs.com/sae-dev-test/langgenius:dify-web
        imagePullPolicy: Always
        name: main
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "4"
            memory: 8Gi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30