apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sae.aliyun.com/micro-registration: "0"
    sae.aliyun.com/nas-mount: '[{"mountDomain":"${NAS_MOUNT_DOMAIN}","mountPath":"/app/api/storage","nasId":"${NAS_ID}","nasPath":"app/api/storage","readOnly":false,"volumeName":"nas-1"}]'
    sae.aliyun.com/pvtz-discovery-svc: '{"enable":"true","namespaceId":"${REGION_ID}:${NAMESPACE}","portAndProtocol":{"5001:TCP":"5001"},"portProtocols":[],"pvtzDiscoveryName":"${REGION_ID}-${ACCOUNT_ID}","serviceName":"dify-api.${NAMESPACE}"}'
    sae.aliyun.com/security-group-id: ${SECURITY_GROUP_ID}
    sae.aliyun.com/timezone: Asia/Shanghai
    sae.aliyun.com/type: Image
    sae.aliyun.com/vpc-id: ${VPC_ID}
    sae.aliyun.com/vswitch-list: ${VSWITCH_LIST}
  name: dify-api
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      sae.aliyun.com/app-name: dify-api
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        sae.aliyun.com/app-name: dify-api
    spec:
      containers:
      - env:
        - name: APP_WEB_URL
        - name: FILES_URL
        - name: CODE_MAX_DEPTH
          value: "5"
        - name: CODE_MAX_OBJECT_ARRAY_LENGTH
          value: "30"
        - name: CHECK_UPDATE_URL
        - name: CODE_MAX_STRING_ARRAY_LENGTH
          value: "30"
        - name: SERVICE_API_URL
        - name: CODE_MAX_PRECISION
          value: "20"
        - name: CONSOLE_API_URL
        - name: TEMPLATE_TRANSFORM_MAX_LENGTH
          value: "80000"
        - name: CODE_MAX_NUMBER
          value: "9223372036854775807"
        - name: CODE_MAX_NUMBER_ARRAY_LENGTH
          value: "1000"
        - name: CONSOLE_WEB_URL
        - name: CODE_MIN_NUMBER
          value: "-9223372036854775808"
        - name: CODE_MAX_STRING_LENGTH
          value: "80000"
        envFrom:
        - secretRef:
            name: dify-credentials
        - secretRef:
            name: dify-api
        - configMapRef:
            name: dify-api
        image: ${DIFY_API_IMAGE}
        imagePullPolicy: Always
        name: main
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "4"
            memory: 8Gi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30