apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sae.aliyun.com/micro-registration: "0"
    sae.aliyun.com/security-group-id: ${SECURITY_GROUP_ID}
    sae.aliyun.com/timezone: Asia/Shanghai
    sae.aliyun.com/type: Image
    sae.aliyun.com/vpc-id: ${VPC_ID}
    sae.aliyun.com/vswitch-list: ${VSWITCH_LIST}
  name: dify-nginx
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      sae.aliyun.com/app-name: dify-nginx
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        sae.aliyun.com/app-name: dify-nginx
    spec:
      containers:
      - image: ${DIFY_NGINX_IMAGE}
        imagePullPolicy: Always
        name: main
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "4"
            memory: 8Gi
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: dify-nginx
          subPath: nginx.conf
        - mountPath: /etc/nginx/proxy.conf
          name: dify-nginx
          subPath: proxy.conf
        - mountPath: /etc/nginx/conf.d/default.conf
          name: dify-nginx
          subPath: default.conf
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: dify-nginx
        name: dify-nginx