apiVersion: v1
data:
  CODE_EXECUTION_ENDPOINT: http://dify-sandbox:8194
  CONSOLE_CORS_ALLOW_ORIGINS: '''*'''
  LOG_LEVEL: DEBUG
  MIGRATION_ENABLED: "true"
  MODE: api
  REDIS_DB: "0"
  REDIS_USE_SSL: "false"
  SENTRY_PROFILES_SAMPLE_RATE: "1.0"
  SENTRY_TRACES_SAMPLE_RATE: "1.0"
  STORAGE_LOCAL_PATH: /app/api/storage
  STORAGE_TYPE: local
  WEB_API_CORS_ALLOW_ORIGINS: '''*'''
kind: ConfigMap
metadata:
  annotations:
  name: dify-api
  namespace: ${NAMESPACE}