apiVersion: v1
kind: Service
metadata:
  annotations:
    sae.aliyun.com/loadbalancer-address-type: internet
  labels:
    sae.aliyun.com/app-name: dify-nginx
  name: internet-dify-nginx
  namespace: ${NAMESPACE}
spec:
  ports:
  - name: port-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    sae.aliyun.com/app-name: dify-nginx
  type: LoadBalancer