apiVersion: v1
data:
  ANALYTICDB_INSTANCE_ID: ${ANALYTICDB_INSTANCE_ID}
  ANALYTICDB_REGION_ID: ${ANALYTICDB_REGION_ID}
  CODE_EXECUTION_ENDPOINT: http://dify-sandbox:8194
  CONSOLE_CORS_ALLOW_ORIGINS: '*'
  DB_DATABASE: ${DB_DATABASE_NAME}
  DB_HOST: ${DB_HOST}
  DB_PORT: "5432"
  LOG_LEVEL: INFO
  MAIL_DEFAULT_SEND_FROM: 'YOUR EMAIL FROM (eg: no-reply <no-reply@dify.ai>)'
  MAIL_TYPE: resend
  MARKETPLACE_ENABLED: "true"
  MIGRATION_ENABLED: "true"
  MODE: api
  PLUGIN_DAEMON_URL: http://dify-plugin-daemon:5002
  REDIS_DB: "0"
  REDIS_HOST: ${REDIS_HOST}
  REDIS_PORT: "6379"
  REDIS_USE_SSL: "false"
  RESEND_API_URL: https://api.resend.com
  SENTRY_PROFILES_SAMPLE_RATE: "1.0"
  SENTRY_TRACES_SAMPLE_RATE: "1.0"
  STORAGE_LOCAL_PATH: /app/api/storage
  STORAGE_TYPE: local
  VECTOR_STORE: analyticdb
  WEB_API_CORS_ALLOW_ORIGINS: '*'
kind: ConfigMap
metadata:
  name: dify-api
  namespace: ${NAMESPACE}
---
apiVersion: v1
data:
  default.conf: "server {\n        listen 80;\n        server_name _;\n    \n        location
    /console/api {\n          proxy_pass http://dify-api:5001;\n          include
    proxy.conf;\n        }\n    \n        location /api {\n          proxy_pass http://dify-api:5001;\n
    \         include proxy.conf;\n        }\n    \n        location /v1 {\n          proxy_pass
    http://dify-api:5001;\n          include proxy.conf;\n        }\n    \n        location
    /files {\n          proxy_pass http://dify-api:5001;\n          include proxy.conf;\n
    \       }\n        \n        location /explore {\n          proxy_pass http://dify-web:3000;\n
    \         proxy_set_header Dify-Hook-Url $scheme://$host$request_uri;\n          include
    proxy.conf;\n        }\n        \n        location /e/ {\n          proxy_pass
    http://dify-plugin-daemon:5002;\n          proxy_set_header Dify-Hook-Url $scheme://$host$request_uri;\n
    \         include proxy.conf;\n        }\n    \n        location / {\n          proxy_pass
    http://dify-web:3000;\n          include proxy.conf;\n        }\n    }"
  nginx.conf: "user  nginx;\n    worker_processes  auto;\n    pid        /var/run/nginx.pid;\n
    \   \n    \n    events {\n        worker_connections  1024;\n    }\n    \n    \n
    \   http {\n        include       /etc/nginx/mime.types;\n        default_type
    \ application/octet-stream;\n    \n        log_format  main  '$remote_addr - $remote_user
    [$time_local] \"$request\" '\n                          '$status $body_bytes_sent
    \"$http_referer\" '\n                          '\"$http_user_agent\" \"$http_x_forwarded_for\"';\n
    \   \n        sendfile        on;\n        #tcp_nopush     on;\n    \n        keepalive_timeout
    \ 65;\n    \n        #gzip  on;\n        client_max_body_size 15M;\n    \n        include
    /etc/nginx/conf.d/*.conf;\n    }"
  proxy.conf: |-
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_buffering off;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
kind: ConfigMap
metadata:
  name: dify-nginx
  namespace: ${NAMESPACE}
---
apiVersion: v1
data:
  DB_DATABASE: ${DB_PLUGIN_DATABASE_NAME}
  DB_HOST: ${DB_HOST}
  DB_PORT: "5432"
  DIFY_INNER_API_URL: http://dify-api:5001
  MARKETPLACE_ENABLED: "true"
  MAX_PLUGIN_PACKAGE_SIZE: "52428800"
  PIP_MIRROR_URL: http://mirrors.aliyun.com/pypi/simple/
  PLUGIN_REMOTE_INSTALLING_HOST: 0.0.0.0
  PLUGIN_REMOTE_INSTALLING_PORT: "5003"
  PLUGIN_WORKING_PATH: /app/storage/cwd
  REDIS_DB: "0"
  REDIS_HOST: ${REDIS_HOST}
  REDIS_PORT: "6379"
  REDIS_USE_SSL: "false"
  SERVER_PORT: "5002"
kind: ConfigMap
metadata:
  name: dify-plugin-daemon
  namespace: ${NAMESPACE}
---
apiVersion: v1
data:
  GIN_MODE: release
  SANDBOX_PORT: "8194"
kind: ConfigMap
metadata:
  name: dify-sandbox
  namespace: ${NAMESPACE}
---
apiVersion: v1
data:
  MARKETPLACE_API_URL: https://marketplace.dify.ai
  MARKETPLACE_ENABLED: "true"
  MARKETPLACE_URL: https://marketplace.dify.ai
kind: ConfigMap
metadata:
  name: dify-web
  namespace: ${NAMESPACE}
---
apiVersion: v1
data:
  ANALYTICDB_INSTANCE_ID: ${ANALYTICDB_INSTANCE_ID}
  ANALYTICDB_REGION_ID: ${REGION_ID}
  CODE_EXECUTION_ENDPOINT: http://dify-sandbox:8194
  CONSOLE_CORS_ALLOW_ORIGINS: '*'
  DB_DATABASE: dify
  DB_HOST: ${DB_HOST}
  DB_PORT: "5432"
  LOG_LEVEL: INFO
  MAIL_DEFAULT_SEND_FROM: 'YOUR EMAIL FROM (eg: no-reply <no-reply@dify.ai>)'
  MAIL_TYPE: resend
  MARKETPLACE_ENABLED: "true"
  MIGRATION_ENABLED: "true"
  MODE: worker
  PLUGIN_DAEMON_URL: http://dify-plugin-daemon:5002
  REDIS_DB: "0"
  REDIS_HOST: ${REDIS_HOST}
  REDIS_PORT: "6379"
  REDIS_USE_SSL: "false"
  RESEND_API_URL: https://api.resend.com
  SENTRY_PROFILES_SAMPLE_RATE: "1"
  SENTRY_TRACES_SAMPLE_RATE: "1"
  STORAGE_LOCAL_PATH: /app/api/storage
  STORAGE_TYPE: local
  VECTOR_STORE: analyticdb
  WEB_API_CORS_ALLOW_ORIGINS: '*'
kind: ConfigMap
metadata:
  name: dify-worker
  namespace: ${NAMESPACE}