apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sae.aliyun.com/language: other
    sae.aliyun.com/micro-registration: "0"
    sae.aliyun.com/nas-mount: '[{"mountDomain":"${API_NAS_MOUNT_DOMAIN}","mountPath":"/app/api/storage","nasId":"${API_NAS_ID}","nasPath":"app/api/storage","readOnly":false,"volumeName":"nas-1"}]'
    sae.aliyun.com/new-sae-version: std
    sae.aliyun.com/pvtz-discovery-svc: '{"enable":"true","namespaceId":"${REGION_ID}:${NAMESPACE}","portAndProtocol":{"5001:TCP":"5001"},"portProtocols":[],"pvtzDiscoveryName":"${REGION_ID}-${ACCOUNT_ID}","serviceName":"dify-api.${NAMESPACE}"}'
    sae.aliyun.com/security-group-id: ${SECURITY_GROUP_ID}
    sae.aliyun.com/timezone: Asia/Shanghai
    sae.aliyun.com/type: Image
    sae.aliyun.com/vpc-id: ${VPC_ID}
    sae.aliyun.com/vswitch-list: ${VSWITCH_LIST}
  name: dify-api
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      sae.aliyun.com/app-name: dify-api
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        sae.aliyun.com/app-name: dify-api
    spec:
      containers:
        - env:
            - name: APP_WEB_URL
            - name: FILES_URL
            - name: CODE_MAX_DEPTH
              value: "5"
            - name: CODE_MAX_OBJECT_ARRAY_LENGTH
              value: "30"
            - name: CHECK_UPDATE_URL
            - name: CODE_MAX_STRING_ARRAY_LENGTH
              value: "30"
            - name: SERVICE_API_URL
            - name: CODE_MAX_PRECISION
              value: "20"
            - name: CONSOLE_API_URL
            - name: TEMPLATE_TRANSFORM_MAX_LENGTH
              value: "80000"
            - name: CODE_MAX_NUMBER
              value: "9223372036854775807"
            - name: CODE_MAX_NUMBER_ARRAY_LENGTH
              value: "1000"
            - name: CONSOLE_WEB_URL
            - name: CODE_MIN_NUMBER
              value: "-9223372036854775808"
            - name: CODE_MAX_STRING_LENGTH
              value: "80000"
            - name: SENTRY_DSN
            - name: CODE_EXECUTION_API_KEY
              valueFrom:
                secretKeyRef:
                  key: API_KEY
                  name: dify-sandbox
          envFrom:
            - configMapRef:
                name: dify-api
            - secretRef:
                name: dify-api
          image: registry.${REGION_ID}.aliyuncs.com/sae-serverless-demo/sae-demo:dify-api-v1.1.3
          imagePullPolicy: Always
          name: main
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: "4"
              memory: 8Gi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sae.aliyun.com/language: other
    sae.aliyun.com/micro-registration: "0"
    sae.aliyun.com/new-sae-version: std
    sae.aliyun.com/security-group-id: ${SECURITY_GROUP_ID}
    sae.aliyun.com/timezone: Asia/Shanghai
    sae.aliyun.com/type: Image
    sae.aliyun.com/vpc-id: ${VPC_ID}
    sae.aliyun.com/vswitch-list: ${VSWITCH_LIST}
  name: dify-nginx
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      sae.aliyun.com/app-name: dify-nginx
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        sae.aliyun.com/app-name: dify-nginx
    spec:
      containers:
        - image: registry.${REGION_ID}.aliyuncs.com/sae-serverless-demo/sae-demo:nginx-v1.23.4
          imagePullPolicy: Always
          name: main
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: "4"
              memory: 8Gi
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: dify-nginx
              subPath: nginx.conf
            - mountPath: /etc/nginx/proxy.conf
              name: dify-nginx
              subPath: proxy.conf
            - mountPath: /etc/nginx/conf.d/default.conf
              name: dify-nginx
              subPath: default.conf
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            name: dify-nginx
          name: dify-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sae.aliyun.com/language: other
    sae.aliyun.com/micro-registration: "0"
    sae.aliyun.com/nas-mount: '[{"mountDomain":"${PLUGIN_NAS_MOUNT_DOMAIN}","mountPath":"/app/storage","nasId":"${PLUGIN_NAS_ID}","nasPath":"app/storage","readOnly":false,"volumeName":"nas-1"}]'
    sae.aliyun.com/new-sae-version: std
    sae.aliyun.com/pvtz-discovery-svc: '{"enable":"true","namespaceId":"${REGION_ID}:${NAMESPACE}","portAndProtocol":{"5003:TCP":"5003","5002:TCP":"5002"},"portProtocols":[],"pvtzDiscoveryName":"${REGION_ID}-${ACCOUNT_ID}","serviceName":"dify-plugin-daemon.${NAMESPACE}"}'
    sae.aliyun.com/security-group-id: ${SECURITY_GROUP_ID}
    sae.aliyun.com/timezone: Asia/Shanghai
    sae.aliyun.com/type: Image
    sae.aliyun.com/vpc-id: ${VPC_ID}
    sae.aliyun.com/vswitch-list: ${VSWITCH_LIST}
  name: dify-plugin-daemon
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      sae.aliyun.com/app-name: dify-plugin-daemon
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        sae.aliyun.com/app-name: dify-plugin-daemon
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: dify-plugin-daemon
            - configMapRef:
                name: dify-plugin-daemon
          image: registry.${REGION_ID}.aliyuncs.com/sae-serverless-demo/sae-demo:dify-plugin-daemon-v0.0.6-local
          imagePullPolicy: Always
          name: main
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: "4"
              memory: 8Gi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sae.aliyun.com/language: other
    sae.aliyun.com/micro-registration: "0"
    sae.aliyun.com/new-sae-version: std
    sae.aliyun.com/pvtz-discovery-svc: '{"enable":"true","namespaceId":"${REGION_ID}:${NAMESPACE}","portAndProtocol":{"8194:TCP":"8194"},"portProtocols":[],"pvtzDiscoveryName":"${REGION_ID}-${ACCOUNT_ID}","serviceName":"dify-sandbox.${NAMESPACE}"}'
    sae.aliyun.com/security-group-id: ${SECURITY_GROUP_ID}
    sae.aliyun.com/timezone: Asia/Shanghai
    sae.aliyun.com/type: Image
    sae.aliyun.com/vpc-id: ${VPC_ID}
    sae.aliyun.com/vswitch-list: ${VSWITCH_LIST}
  name: dify-sandbox
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      sae.aliyun.com/app-name: dify-sandbox
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        sae.aliyun.com/app-name: dify-sandbox
    spec:
      containers:
        - env:
            - name: WORKER_TIMEOUT
              value: "15"
          envFrom:
            - secretRef:
                name: dify-sandbox
            - configMapRef:
                name: dify-sandbox
          image: registry.${REGION_ID}.aliyuncs.com/sae-serverless-demo/sae-demo:dify-sandbox-v0.2.11
          imagePullPolicy: Always
          name: main
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: "4"
              memory: 8Gi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sae.aliyun.com/language: other
    sae.aliyun.com/micro-registration: "0"
    sae.aliyun.com/new-sae-version: std
    sae.aliyun.com/pvtz-discovery-svc: '{"enable":"true","namespaceId":"${REGION_ID}:${NAMESPACE}","portAndProtocol":{"3000:TCP":"3000"},"portProtocols":[],"pvtzDiscoveryName":"${REGION_ID}-${ACCOUNT_ID}","serviceName":"dify-web.${NAMESPACE}"}'
    sae.aliyun.com/security-group-id: ${SECURITY_GROUP_ID}
    sae.aliyun.com/timezone: Asia/Shanghai
    sae.aliyun.com/type: Image
    sae.aliyun.com/vpc-id: ${VPC_ID}
    sae.aliyun.com/vswitch-list: ${VSWITCH_LIST}
  name: dify-web
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      sae.aliyun.com/app-name: dify-web
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        sae.aliyun.com/app-name: dify-web
    spec:
      containers:
        - env:
            - name: APP_API_URL
            - name: CONSOLE_API_URL
            - name: EDITION
              value: SELF_HOSTED
          envFrom:
            - configMapRef:
                name: dify-web
          image: registry.${REGION_ID}.aliyuncs.com/sae-serverless-demo/sae-demo:dify-web-v1.1.3
          imagePullPolicy: Always
          name: main
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: "4"
              memory: 8Gi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sae.aliyun.com/language: other
    sae.aliyun.com/micro-registration: "0"
    sae.aliyun.com/nas-mount: '[{"mountDomain":"${API_NAS_MOUNT_DOMAIN}","mountPath":"/app/api/storage","nasId":"${API_NAS_ID}","nasPath":"app/api/storage","readOnly":false,"volumeName":"nas-1"}]'
    sae.aliyun.com/new-sae-version: std
    sae.aliyun.com/security-group-id: ${SECURITY_GROUP_ID}
    sae.aliyun.com/timezone: Asia/Shanghai
    sae.aliyun.com/type: Image
    sae.aliyun.com/vpc-id: ${VPC_ID}
    sae.aliyun.com/vswitch-list: ${VSWITCH_LIST}
  name: dify-worker
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      sae.aliyun.com/app-name: dify-worker
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        sae.aliyun.com/app-name: dify-worker
    spec:
      containers:
        - env:
            - name: CONSOLE_WEB_URL
          envFrom:
            - secretRef:
                name: dify-worker
            - configMapRef:
                name: dify-worker
          image: registry.${REGION_ID}.aliyuncs.com/sae-serverless-demo/sae-demo:dify-api-v1.1.3
          imagePullPolicy: Always
          name: main
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: "4"
              memory: 8Gi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30