Parameters:
  Region: "cn-hangzhou"
  Name: "start-airflow"
SceneMetadata:
  Name:
    zh-cn: "Airflow"
    en: "Airflow"
  Description:
    zh-cn: "Airflow是一个开源工作流调度平台，用于编排和管理数据管道。"
    en: " Airflow是一个开源工作流调度平台，用于编排和管理数据管道。"
  Logo: "gray/resources/icons/scence_logo.png"
  Visible: true
SceneProfiles:
  - DisplayName:
      zh-cn: Airflow
    DeployType: SaeFlow
    Documentation:
      zh-cn: "gray/docs/zh-cn/index.md"
    Template: "gray/templates/cicd.yml"
    VariableTemplate: "gray/templates/variable.yml"
    FormTemplate: "gray/templates/form.yml"
    FlowTemplate: "gray/templates/msa.yml"
    Spec:
      HEADER: "gray/templates/formCompose/header.spec.yml"
      MYSQL: "gray/templates/formCompose/mysql.spec.yml"
      OSS: "gray/templates/formCompose/oss.spec.yml"


