Parameters:
  Region: "cn-hangzhou"
  Name: "start-dify"
SceneMetadata:
  Name:
    zh-cn: "Dify 社区版"
  Description:
    zh-cn: "Dify.AI 是 LLMOps 平台，简化 AI 应用开发和集成，支持可视化管理。"
  Logo: "resources/icons/scence_logo.png"
SceneProfiles:
  - DisplayName:
      zh-cn: Dify社区版
    DeployType: SaeFlow
    Documentation:
      zh-cn: "docs/zh-cn/index.md"
    Spec: "templates/cicd.spec.yml"
    Template: "templates/msa.yml"

