apiVersion: v1
data:
  default.conf: "server {\n        listen 80;\n        server_name _;\n    \n        location
    /console/api {\n          proxy_pass http://dify-api:5001;\n          include
    proxy.conf;\n        }\n    \n        location /api {\n          proxy_pass http://dify-api:5001;\n
    \         include proxy.conf;\n        }\n    \n        location /v1 {\n          proxy_pass
    http://dify-api:5001;\n          include proxy.conf;\n        }\n    \n        location
    /files {\n          proxy_pass http://dify-api:5001;\n          include proxy.conf;\n
    \       }\n    \n        location / {\n          proxy_pass http://dify-web:3000;\n
    \         include proxy.conf;\n        }\n    }"
  nginx.conf: "user  nginx;\n    worker_processes  auto;\n    pid        /var/run/nginx.pid;\n
    \   \n    \n    events {\n        worker_connections  1024;\n    }\n    \n    \n
    \   http {\n        include       /etc/nginx/mime.types;\n        default_type
    \ application/octet-stream;\n    \n        log_format  main  '$remote_addr - $remote_user
    [$time_local] \"$request\" '\n                          '$status $body_bytes_sent
    \"$http_referer\" '\n                          '\"$http_user_agent\" \"$http_x_forwarded_for\"';\n
    \   \n        sendfile        on;\n        #tcp_nopush     on;\n    \n        keepalive_timeout
    \ 65;\n    \n        #gzip  on;\n        client_max_body_size 15M;\n    \n        include
    /etc/nginx/conf.d/*.conf;\n    }"
  proxy.conf: |-
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_buffering off;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
kind: ConfigMap
metadata:
  name: dify-nginx
  namespace: ${NAMESPACE}